
-- World events generated by the AI DM
CREATE TABLE public.world_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  event_type text NOT NULL DEFAULT 'narrative',
  effects jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '30 minutes'),
  resolved_at timestamptz
);

-- Enable RLS
ALTER TABLE public.world_events ENABLE ROW LEVEL SECURITY;

-- Players can see their own events
CREATE POLICY "Users can view own events" ON public.world_events
FOR SELECT TO authenticated
USING (auth.uid() = user_id);

-- Service role inserts events (from edge function)
CREATE POLICY "Service can insert events" ON public.world_events
FOR INSERT TO service_role
WITH CHECK (true);

-- Users can update own events (to dismiss/resolve)
CREATE POLICY "Users can update own events" ON public.world_events
FOR UPDATE TO authenticated
USING (auth.uid() = user_id);

-- Enable realtime for world_events
ALTER PUBLICATION supabase_realtime ADD TABLE public.world_events;
